#define jinit_read_bmp		IJG12_jIRdBMP
#define jinit_write_bmp		IJG12_jIWrBMP
#define jinit_read_gif		IJG12_jIRdGIF
#define jinit_write_gif		IJG12_jIWrGIF
#define jinit_read_ppm		IJG12_jIRdPPM
#define jinit_write_ppm		IJG12_jIWrPPM
#define jinit_read_rle		IJG12_jIRdRLE
#define jinit_write_rle		IJG12_jIWrRLE
#define jinit_read_targa	IJG12_jIRdTarga
#define jinit_write_targa	IJG12_jIWrTarga
#define read_quant_tables	IJG12_RdQTables
#define read_scan_script	IJG12_RdScnScript
#define set_quality_ratings     IJG12_SetQRates
#define set_quant_slots		IJG12_SetQSlots
#define set_sample_factors	IJG12_SetSFacts
#define read_color_map		IJG12_RdCMap
#define enable_signal_catcher	IJG12_EnSigCatcher
#define start_progress_monitor	IJG12_StProgMon
#define end_progress_monitor	IJG12_EnProgMon
#define read_stdin		IJG12_RdStdin
#define write_stdout		IJG12_WrStdout

#define jpeg_fdct_islow		IJG12_jFDislow
#define jpeg_fdct_ifast		IJG12_jFDifast
#define jpeg_fdct_float		IJG12_jFDfloat
#define jpeg_fdct_7x7		IJG12_jFD7x7
#define jpeg_fdct_6x6		IJG12_jFD6x6
#define jpeg_fdct_5x5		IJG12_jFD5x5
#define jpeg_fdct_4x4		IJG12_jFD4x4
#define jpeg_fdct_3x3		IJG12_jFD3x3
#define jpeg_fdct_2x2		IJG12_jFD2x2
#define jpeg_fdct_1x1		IJG12_jFD1x1
#define jpeg_fdct_9x9		IJG12_jFD9x9
#define jpeg_fdct_10x10		IJG12_jFD10x10
#define jpeg_fdct_11x11		IJG12_jFD11x11
#define jpeg_fdct_12x12		IJG12_jFD12x12
#define jpeg_fdct_13x13		IJG12_jFD13x13
#define jpeg_fdct_14x14		IJG12_jFD14x14
#define jpeg_fdct_15x15		IJG12_jFD15x15
#define jpeg_fdct_16x16		IJG12_jFD16x16
#define jpeg_fdct_16x8		IJG12_jFD16x8
#define jpeg_fdct_14x7		IJG12_jFD14x7
#define jpeg_fdct_12x6		IJG12_jFD12x6
#define jpeg_fdct_10x5		IJG12_jFD10x5
#define jpeg_fdct_8x4		IJG12_jFD8x4
#define jpeg_fdct_6x3		IJG12_jFD6x3
#define jpeg_fdct_4x2		IJG12_jFD4x2
#define jpeg_fdct_2x1		IJG12_jFD2x1
#define jpeg_fdct_8x16		IJG12_jFD8x16
#define jpeg_fdct_7x14		IJG12_jFD7x14
#define jpeg_fdct_6x12		IJG12_jFD6x12
#define jpeg_fdct_5x10		IJG12_jFD5x10
#define jpeg_fdct_4x8		IJG12_jFD4x8
#define jpeg_fdct_3x6		IJG12_jFD3x6
#define jpeg_fdct_2x4		IJG12_jFD2x4
#define jpeg_fdct_1x2		IJG12_jFD1x2
#define jpeg_idct_islow		IJG12_jRDislow
#define jpeg_idct_ifast		IJG12_jRDifast
#define jpeg_idct_float		IJG12_jRDfloat
#define jpeg_idct_7x7		IJG12_jRD7x7
#define jpeg_idct_6x6		IJG12_jRD6x6
#define jpeg_idct_5x5		IJG12_jRD5x5
#define jpeg_idct_4x4		IJG12_jRD4x4
#define jpeg_idct_3x3		IJG12_jRD3x3
#define jpeg_idct_2x2		IJG12_jRD2x2
#define jpeg_idct_1x1		IJG12_jRD1x1
#define jpeg_idct_9x9		IJG12_jRD9x9
#define jpeg_idct_10x10		IJG12_jRD10x10
#define jpeg_idct_11x11		IJG12_jRD11x11
#define jpeg_idct_12x12		IJG12_jRD12x12
#define jpeg_idct_13x13		IJG12_jRD13x13
#define jpeg_idct_14x14		IJG12_jRD14x14
#define jpeg_idct_15x15		IJG12_jRD15x15
#define jpeg_idct_16x16		IJG12_jRD16x16
#define jpeg_idct_16x8		IJG12_jRD16x8
#define jpeg_idct_14x7		IJG12_jRD14x7
#define jpeg_idct_12x6		IJG12_jRD12x6
#define jpeg_idct_10x5		IJG12_jRD10x5
#define jpeg_idct_8x4		IJG12_jRD8x4
#define jpeg_idct_6x3		IJG12_jRD6x3
#define jpeg_idct_4x2		IJG12_jRD4x2
#define jpeg_idct_2x1		IJG12_jRD2x1
#define jpeg_idct_8x16		IJG12_jRD8x16
#define jpeg_idct_7x14		IJG12_jRD7x14
#define jpeg_idct_6x12		IJG12_jRD6x12
#define jpeg_idct_5x10		IJG12_jRD5x10
#define jpeg_idct_4x8		IJG12_jRD4x8
#define jpeg_idct_3x6		IJG12_jRD3x8
#define jpeg_idct_2x4		IJG12_jRD2x4
#define jpeg_idct_1x2		IJG12_jRD1x2

#define jpeg_std_message_table	IJG12_jMsgTable

#define jpeg_get_small		IJG12_jGetSmall
#define jpeg_free_small		IJG12_jFreeSmall
#define jpeg_get_large		IJG12_jGetLarge
#define jpeg_free_large		IJG12_jFreeLarge
#define jpeg_mem_available	IJG12_jMemAvail
#define jpeg_open_backing_store	IJG12_jOpenBackStore
#define jpeg_mem_init		IJG12_jMemInit
#define jpeg_mem_term		IJG12_jMemTerm

#define jinit_compress_master	IJG12_jICompress
#define jinit_c_master_control	IJG12_jICMaster
#define jinit_c_main_controller	IJG12_jICMainC
#define jinit_c_prep_controller	IJG12_jICPrepC
#define jinit_c_coef_controller	IJG12_jICCoefC
#define jinit_color_converter	IJG12_jICColor
#define jinit_downsampler	IJG12_jIDownsampler
#define jinit_forward_dct	IJG12_jIFDCT
#define jinit_huff_encoder	IJG12_jIHEncoder
#define jinit_arith_encoder	IJG12_jIAEncoder
#define jinit_marker_writer	IJG12_jIMWriter
#define jinit_master_decompress	IJG12_jIDMaster
#define jinit_d_main_controller	IJG12_jIDMainC
#define jinit_d_coef_controller	IJG12_jIDCoefC
#define jinit_d_post_controller	IJG12_jIDPostC
#define jinit_input_controller	IJG12_jIInCtlr
#define jinit_marker_reader IJG12_jIMReader
#define jinit_huff_decoder	IJG12_jIHDecoder
#define jinit_arith_decoder	IJG12_jIADecoder
#define jinit_inverse_dct	IJG12_jIIDCT
#define jinit_upsampler		IJG12_jIUpsampler
#define jinit_color_deconverter	IJG12_jIDColor
#define jinit_1pass_quantizer	IJG12_jI1Quant
#define jinit_2pass_quantizer	IJG12_jI2Quant
#define jinit_merged_upsampler	IJG12_jIMUpsampler
#define jinit_memory_mgr	IJG12_jIMemMgr
#define jdiv_round_up		IJG12_jDivRound
#define jround_up		IJG12_jRound
#define jzero_far		IJG12_jZeroFar
#define jcopy_sample_rows	IJG12_jCopySamples
#define jcopy_block_row		IJG12_jCopyBlocks
#define jpeg_zigzag_order	IJG12_jZIGTable
#define jpeg_natural_order	IJG12_jZAGTable
#define jpeg_natural_order7	IJG12_jZAG7Table
#define jpeg_natural_order6	IJG12_jZAG6Table
#define jpeg_natural_order5	IJG12_jZAG5Table
#define jpeg_natural_order4	IJG12_jZAG4Table
#define jpeg_natural_order3	IJG12_jZAG3Table
#define jpeg_natural_order2	IJG12_jZAG2Table
#define jpeg_aritab		IJG12_jAriTab

#define jpeg_std_error		IJG12_jStdError
#define jpeg_CreateCompress	IJG12_jCreaCompress
#define jpeg_CreateDecompress	IJG12_jCreaDecompress
#define jpeg_destroy_compress	IJG12_jDestCompress
#define jpeg_destroy_decompress	IJG12_jDestDecompress
#define jpeg_stdio_dest		IJG12_jStdDest
#define jpeg_stdio_src		IJG12_jStdSrc
#define jpeg_mem_dest		IJG12_jMemDest
#define jpeg_mem_src		IJG12_jMemSrc
#define jpeg_set_defaults	IJG12_jSetDefaults
#define jpeg_set_colorspace	IJG12_jSetColorspace
#define jpeg_default_colorspace	IJG12_jDefColorspace
#define jpeg_set_quality	IJG12_jSetQuality
#define jpeg_set_linear_quality	IJG12_jSetLQuality
#define jpeg_default_qtables	IJG12_jDefQTables
#define jpeg_add_quant_table	IJG12_jAddQuantTable
#define jpeg_quality_scaling	IJG12_jQualityScaling
#define jpeg_simple_progression	IJG12_jSimProgress
#define jpeg_suppress_tables	IJG12_jSuppressTables
#define jpeg_alloc_quant_table	IJG12_jAlcQTable
#define jpeg_alloc_huff_table	IJG12_jAlcHTable
#define jpeg_std_huff_table	IJG12_jStdHTable
#define jpeg_start_compress	IJG12_jStrtCompress
#define jpeg_write_scanlines	IJG12_jWrtScanlines
#define jpeg_finish_compress	IJG12_jFinCompress
#define jpeg_calc_jpeg_dimensions	IJG12_jCjpegDimensions
#define jpeg_write_raw_data	IJG12_jWrtRawData
#define jpeg_write_marker	IJG12_jWrtMarker
#define jpeg_write_m_header	IJG12_jWrtMHeader
#define jpeg_write_m_byte	IJG12_jWrtMByte
#define jpeg_write_tables	IJG12_jWrtTables
#define jpeg_read_header	IJG12_jReadHeader
#define jpeg_start_decompress	IJG12_jStrtDecompress
#define jpeg_read_scanlines	IJG12_jReadScanlines
#define jpeg_finish_decompress	jIJG12_FinDecompress
#define jpeg_read_raw_data	IJG12_jReadRawData
#define jpeg_has_multiple_scans	IJG12_jHasMultScn
#define jpeg_start_output	IJG12_jStrtOutput
#define jpeg_finish_output	IJG12_jFinOutput
#define jpeg_input_complete	IJG12_jInComplete
#define jpeg_new_colormap	IJG12_jNewCMap
#define jpeg_consume_input	IJG12_jConsumeInput
#define jpeg_core_output_dimensions	IJG12_jCoreDimensions
#define jpeg_calc_output_dimensions	IJG12_jCalcDimensions
#define jpeg_save_markers	IJG12_jSaveMarkers
#define jpeg_set_marker_processor	IJG12_jSetMarker
#define jpeg_read_coefficients	IJG12_jReadCoefs
#define jpeg_write_coefficients	IJG12_jWrtCoefs
#define jpeg_copy_critical_parameters	IJG12_jCopyCrit
#define jpeg_abort_compress	IJG12_jAbrtCompress
#define jpeg_abort_decompress	IJG12_jAbrtDecompress
#define jpeg_abort		IJG12_jAbort
#define jpeg_destroy		IJG12_jDestroy
#define jpeg_resync_to_restart	IJG12_jResyncRestart
#define jtransform_parse_crop_spec	IJG12_jTrParCrop
#define jtransform_request_workspace	IJG12_jTrRequest
#define jtransform_adjust_parameters	IJG12_jTrAdjust
#define jtransform_execute_transform	IJG12_jTrExec
#define jtransform_perfect_transform	IJG12_jTrPerfect
#define jcopy_markers_setup		IJG12_jCMrkSetup
#define jcopy_markers_execute		IJG12_jCMrkExec